---
- src: https://github.com/geerlingguy/ansible-role-docker
  version: master
- src: https://github.com/geerlingguy/ansible-role-pip
  version: master
- src: https://github.com/geerlingguy/ansible-role-git
  version: master
